# Generated by Django 5.1.3 on 2024-11-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_userprofile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(blank=True, max_length=100)),
                ("food_category", models.CharField(blank=True, max_length=100)),
                ("about", models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
