# Generated by Django 5.1.3 on 2024-11-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_restaurantprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(blank=True, max_length=100)),
                ("food_category", models.CharField(blank=True, max_length=100)),
                ("about", models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
