# Generated by Django 5.1.3 on 2024-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_menu_userprofile_name_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurant_picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
    ]
