# Generated by Django 5.1.3 on 2024-11-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_menu_menu_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_picture',
            field=models.ImageField(blank=True, null=True, upload_to='menu_picture/'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='restaurant_picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_picture/'),
        ),
    ]
