# Generated by Django 5.1.3 on 2024-11-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_menu_menu_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantprofile",
            name="open_close_time",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
