# Generated by Django 5.1.3 on 2024-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_restaurantprofile_open_close_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
