# Generated by Django 5.1.1 on 2024-11-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_restaurantprofile_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("open_close_time", models.CharField(max_length=50)),
            ],
        ),
    ]
