# Generated by Django 5.1.3 on 2024-11-23 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_foodcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
        ),
    ]
