# Generated by Django 5.1.3 on 2024-11-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_menu_food_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantprofile",
            name="food_category",
            field=models.CharField(
                choices=[
                    ("ข้าวราดแกง", "ข้าวราดแกง"),
                    ("อาหารตามสั่ง", "อาหารตามสั่ง"),
                    ("ขนมหวาน", "ขนมหวาน"),
                ],
                default="ข้าวราดแกง",
                max_length=50,
            ),
        ),
    ]
