# Generated by Django 5.1.3 on 2024-11-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_menu_food_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantprofile",
            name="food_category",
            field=models.CharField(
                choices=[
                    ("เลือกประเภทอาหาร", "เลือกประเภทอาหาร"),
                    ("ข้าวราดแกง", "ข้าวราดแกง"),
                    ("อาหารตามสั่ง", "อาหารตามสั่ง"),
                    ("ขนมหวาน", "ขนมหวาน"),
                    ("น้ำ", "น้ำ"),
                    ("ก๋วยเตี๋ยว", "ก๋วยเตี๋ยว"),
                    ("อาหารญี่ปุ่น", "อาหารญี่ปุ่น"),
                    ("ของกินเล่น", "ของกินเล่น"),
                ],
                default="เลือกประเภทอาหาร",
                max_length=50,
            ),
        ),
    ]
