# Generated by Django 5.1.3 on 2024-11-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_restaurantprofile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurant_picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_picture/'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
        ),
    ]
