# Generated by Django 5.1.3 on 2024-11-23 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_menu_food_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="restaurant_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="home.restaurantprofile",
            ),
        ),
    ]
