# Generated by Django 5.1.3 on 2024-11-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_restaurantprofile_restaurant_picture_and_more'),
        ('home', '0022_menu_restaurant_profile'),
    ]

    operations = [
    ]
