# Generated by Django 5.1.3 on 2024-11-24 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_merge_20241124_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='food_category',
            field=models.CharField(choices=[('เลือกประเภทอาหาร', 'เลือกประเภทอาหาร'), ('ข้าวราดแกง', 'ข้าวราดแกง'), ('อาหารตามสั่ง', 'อาหารตามสั่ง'), ('ขนมหวาน', 'ขนมหวาน'), ('น้ำ', 'น้ำ'), ('ก๋วยเตี๋ยว', 'ก๋วยเตี๋ยว'), ('อาหารญี่ปุ่น', 'อาหารญี่ปุ่น'), ('ของกินเล่น', 'ของกินเล่น')], default='เลือกประเภทอาหาร', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='open_close_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='restaurant_picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_pictures/'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
        ),
    ]
