# Generated by Django 5.1.3 on 2024-11-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_alter_restaurantprofile_about_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="FoodCategory",
        ),
    ]
