# Generated by Django 5.1.3 on 2024-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_order_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('in_store', 'Pick up in store'), ('takeaway', 'Takeaway')], default='in_store', max_length=10),
        ),
    ]
