# Generated by Django 5.1.3 on 2024-12-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_order_payment_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for Payment'), ('waiting_for_approve', 'Waiting for Approve'), ('paid', 'Paid'), ('cooking', 'Cooking'), ('completed', 'Completed')], default='waiting_for_payment', max_length=20),
        ),
    ]
