# Generated by Django 5.1.3 on 2024-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cooking', 'Cooking'), ('waiting_for_payment', 'Waiting for Payment'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
